libbpf_path: /usr/lib64/libbpf.so
bpf_virtual_fs_path: /sys/fs/bpf
if_config_path: if_attach_list.config

#pin object python 的参数和 c 文件参数的同步问题，我再想想怎么解决, 
#一个可能的方案是，通过 编译 -D 选项传进去，然后用 python脚本在顶层进行编译
#暂时先保存两份

progect_pin_prefix: mptcp_ebpf_control_frame

#define
max_subflow_num: 200000
max_xdp_action_num: 32
subflow_max_action_num: 4
subflow_param_bytes: 20